### ISSUE TITLE
Using a single connection to handle events + run commands?

### ISSUE THREAD

**Issue by yaymukund** [JayceFayne/swayipc-rs#25]
Currently, it is not possible to use a single connection to both listen for events and run commands. This is because `connection.subscribe()` consumes `self`.

Is it possible / is there a plan to support using a single `Connection`? Perhaps it could look like this:

```rust
async fn subscribe(&mut self) -> Fallible<Events> { ... }
async fn get_tree(&mut self) -> Fallible<Node> { ... }
```

I'm not sure how this would work under Rust's ownership model, but I'm curious to hear what you think. Thanks!

**Comment by JayceFayne** [comment]
Hey, I have no plans on implementing this since it would increase code complexity and runtime cost unnecessary imo. The reason why is because using the same connection for running commands and receiving events can lead to race conditions. This is by design and mentioned in the i3ipc docs [here](https://i3wm.org/docs/ipc.html#_events)

> Caveat: As soon as you subscribe to an event, it is not guaranteed any longer that the requests to i3 are processed in order. This means, the following situation can happen: You send a GET_WORKSPACES request but you receive a "workspace" event before receiving the reply to GET_WORKSPACES. If your program does not want to cope which such kinds of race conditions (an event based library may not have a problem here), I suggest you create a separate connection to receive events.

One could design the library to detect such race conditions and handle them gracefully...and like you already mentioned:

> I'm not sure how this would work under Rust's ownership model, but I'm curious to hear what you think.

This would be another problem. I guess the easiest way to workaround this is by wrapping the `UnixStream` with `Arc` and `Mutex`. This would change all functions from taking `&mut self` to just `&self`. In the end it would add further complexity and runtime cost. Creating a second connection for event listening is therefore a more pragmatic way to handle situations that need event listening and command execution at the same time

**Comment by yaymukund** [comment]
In theory, I think you could distinguish between the workspace event and the `GET_WORKSPACES` reply by checking its type. Then, I think you'd need some kind of buffer to store the events you might receive while checking for command replies.

That said, I agree with your conclusion that it's not worth the additional complexity, at least not for my use case. Thanks for writing down your thinking around this and for linking to the docs. I'll close this issue now :)
